# (IMPORTANT) But wait! Start the cache first! To improve subsequent rebuild time yess.
      - name: Cache da right now!
        id: cache-da-right-now
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/SparsdatField
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

# Okay fine, start again from scratch. make the AppImage?
      # peck! it requires an old VST2 SDK.
      - name: Build AppImage
        run: |
          cd ~/SparsdatField/Element/
          pwd
          ls
          echo "First, makesure all sh files are executable"
          echo "https://phoenixnap.com/kb/chmod-recursive"
          find . -name "*.sh" -exec chmod +x {} \;
          ./tools/buildall-linux.sh

      - name: list Build folder again. what does this contains now?
        run: |
          cd ~/SparsdatField/Element/build
          pwd
          ls -R -lh
      
      - name: Watermark our name again because the build all linux sh deleted everything build folder!
        run: |
          cp ~/work/Sparsdator/Sparsdator/PressKit/X0P1R4T3_eenvreensment.md ~/SparsdatField/Element/build
          cp ~/work/Sparsdator/Sparsdator/PressKit/X0P1R4T3_eenvreensment.txt ~/SparsdatField/Element/build
      
      - name: Artifact element again
        uses: actions/upload-artifact@v2.3.1
        with:
          # Artifact name
          name: KUSHVIEW-ELEMENT-APPIMAGE-FULLVERSION-FREE-NO_VIRUS-NO_PASSWORD-GitHubAction
          # A file, directory or wildcard pattern that describes what to upload
          path: ~/SparsdatField/Element/build

      - name: Then set everything MinGW up
        run: |
          mingw
          pacman -Syu
          exit
          mingw
          pacman -Su
          exit
          mingw
      
      - name: Install MinGW packages now!
        run: |
          mingw
          echo "Begin Installation of packages now"
          pacman -S \
          mingw-w64-x86_64-toolchain \
          python3 \
          python3-setuptools \
          mingw-w64-x86_64-python3 \
          mingw-w64-x86_64-python3-setuptools \
          python2 \
          python2-setuptools \
          pkg-config \
          mingw-w64-x86_64-pkg-config \
          autoconf \
          automake \
          perl \
          gtk-doc \
          flex \
          bison \
          patch \
          libtool \
          mingw-w64-x86_64-libtool \
          wget \
          git \
          nasm \
          mingw-w64-x86_64-nasm \
          dos2unix \
          mingw-w64-x86_64-cmake
      
      - name: Dependencies Too!
        run: |
          mingw