name: Greetings Fellow Sparsdators

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thancc for your the issue. Taking a look at it.'
        pr-message: 'Thancc for your pull request. Taking a look at it.'
